language: java
jdk:
- openjdk8
os:
- linux
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: D9wFxCM6ElgeqRmFlnfi0aWqJvQHEoyd6soPjBYxSY4YxKmdWyn4F44Uq5dkMEqjd7dcuxBKuvHOWp/DlJwpnPrlCI/CEeVEjRFe3zyBTuTOYHfgLJUPza/VbkDmk8NuLYO1lxzA+hpWYcOmxN9Dma6Kf8oDmvsSdClHyce4ZzaoSln8LlcJhVCRFDArqq+uM1SpOvIYWTVTPmp6jNnBkALPOfwF07xJFy3ndLQSK70P59I5fiqhlaLILu8qZpkwHGJ/+bj8NZumj04UYLf3rkyKmnvf6zIor+p16NIg0kDKelzXvMxStUTi5vH2I7MdGsu5wQjuup0J0E+DTHUbHIz5OSiMmKssLuPHiokVEJskQ4ixUcXji0rErk4P4Hv5/ZCjOzM3WQ6Vvk6lXKkI6DataMG21P0wOzvYKN/0Z5x4MAMiKRPD7Qd6/A0bucvdCDIb2m+oRmxtjDeXdRL0F02tIEn2Eu/QhM3POySDnvXw2uw87aF1vBDdWWoe1bg02MRYMOy5nmhwlE6Tnij9aqLUogD/X6QgjfEJ1E48GUny2dTBktb1fUio8Ui0jRAfR7rEcpTtsNu/ajzwzr9DhLm52NYtT5kMw9iPCBlvtKEQRise0y+JmrdgESN0ovh0bA6O9vi1VlNA3+PZ/+Qkyxg9hDnHnwSk3xFa6Q0eLfM=
  app: tweetboot-kiran
  on: main
branches:
  only:
    - main